<x-lareon::admin-layout>
    @section('title', __('log') . '-' . $name)
    @section('description', __('a log file is a record of events, activities, or errors generated by the application or server for monitoring and debugging purposes'))
    @section('header.start')
        <form action="" method="get" id="changeLog">
            <x-lareon::input.select class="block w-full" name="log" onchange="this.form.submit()"
                                    aria-label="{{__('logs')}}">
                @foreach($logs ?? [] as $file)
                    <option
                        value="{{$file}}" {{request()->input('log' ,'laravel') == $file ? 'selected' : ''}}>{{$file}}</option>
                @endforeach
            </x-lareon::input.select>
        </form>
    @endsection

    @section('header.end')
        @can('admin.setting.log.clear')
            <form action="{{route('admin.settings.logs.clear')}}" method="POST">
                @csrf
                @method('delete')
                <input type="hidden" class="hidden" name="log" value="{{$name}}">
                <x-lareon::button.solid color="red">
                    {{__('clear')}}
                </x-lareon::button.solid>
            </form>
        @endcan
        @can('admin.setting.log.delete')
            <form action="{{route('admin.settings.logs.destroy')}}" method="POST">
                @csrf
                @method('delete')
                <input type="hidden" class="hidden" name="log" value="{{$name}}">
                <x-lareon::button.outline color="red">
                    {{__('delete')}}
                </x-lareon::button.outline>
            </form>
        @endcan

    @endsection
    <section class="mb-6">
        <div class="bg-zinc-900 text-gray-400 font-semibold p-6 rounded-lg w-full max-h-screen overflow-auto" dir="ltr">
            <pre>{!! $content !!}</pre>
        </div>
    </section>
</x-lareon::admin-layout>
